# Generated by Django 6.0.5 on 2026-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reyting',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
